'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { PASSWORD_MAX_LENGTH, PASSWORD_MIN_LENGTH, validateLoginPasswordValue } from '@/lib/auth/password-policy';

const mainlandPhone = /^1[3-9]\d{9}$/;
export default function ForgotPasswordPage() {
  const router = useRouter();
  const [phone, setPhone] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [countdown, setCountdown] = useState(0); const [sending, setSending] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { if (!countdown) return; const timer = window.setInterval(() => setCountdown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [countdown]);
  async function sendCode() { setError(''); if (!mainlandPhone.test(phone)) return setError('请输入有效的中国大陆手机号'); setSending(true); try { const response = await fetch('/api/auth/forgot-password/send-code', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone }) }); const data = await response.json().catch(() => null); if (!response.ok) return setError(data?.error || '短信暂时发送失败'); setCountdown(60); setMessage('验证码已发送。'); } catch { setError('网络异常，请稍后重试'); } finally { setSending(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); const passwordIssue = validateLoginPasswordValue(password); if (passwordIssue) return setError(passwordIssue); if (password !== confirmPassword) return setError('两次密码输入不一致'); setSaving(true); try { const response = await fetch('/api/auth/forgot-password/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone, code, password, confirmPassword }) }); const data = await response.json().catch(() => null); if (!response.ok) return setError(data?.error || '设置密码失败'); router.replace('/auth/login'); } catch { setError('网络异常，请稍后重试'); } finally { setSaving(false); } }
  return <div className="w-full max-w-md"><h1 className="mb-2 text-center text-2xl font-bold text-text-primary">设置登录密码</h1><p className="mb-8 text-center text-sm text-text-secondary">验证手机号后设置或重置密码，原有登录会话将失效。</p><form className="space-y-4" onSubmit={submit}><input className="input-primary" inputMode="numeric" maxLength={11} placeholder="中国大陆手机号" value={phone} onChange={(event) => setPhone(event.target.value.replace(/\D/g, ''))} /><div className="relative"><input className="input-primary pr-28" inputMode="numeric" maxLength={6} placeholder="6 位验证码" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} /><button className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-accent-blue disabled:text-text-muted" type="button" onClick={sendCode} disabled={sending || countdown > 0}>{countdown ? `${countdown}s 后重试` : sending ? '发送中' : '获取验证码'}</button></div><input className="input-primary" type="password" autoComplete="new-password" maxLength={PASSWORD_MAX_LENGTH} placeholder={`新密码（至少 ${PASSWORD_MIN_LENGTH} 位，含两种字符类型）`} value={password} onChange={(event) => setPassword(event.target.value)} /><input className="input-primary" type="password" autoComplete="new-password" maxLength={PASSWORD_MAX_LENGTH} placeholder="确认新密码" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} />{message && <p className="text-sm text-success">{message}</p>}{error && <p className="text-sm text-danger">{error}</p>}<button className="btn-primary w-full rounded-xl py-3 disabled:opacity-60" disabled={saving}>{saving ? '处理中…' : '设置密码'}</button></form><p className="mt-6 text-center text-sm"><Link className="text-accent-blue" href="/auth/login">返回登录</Link></p></div>;
}
