'use client';
import { useEffect, useState } from 'react';
import { Loader2, ShieldCheck } from 'lucide-react';

export default function BillingOperations() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [reason, setReason] = useState(''); const [companyId, setCompanyId] = useState(''); const [amount, setAmount] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { const res = await fetch('/api/admin/billing'); const payload = await res.json(); if (res.ok) setData(payload); else setError(payload.error || '加载失败'); };
  useEffect(() => { load(); }, []);
  const action = async (payload: any) => { if (!reason.trim()) { setError('请填写操作原因'); return; } setBusy(true); const res = await fetch('/api/admin/billing', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, reason }) }); const result = await res.json(); setBusy(false); if (!res.ok) setError(result.error || '操作失败'); else { setError(''); setReason(''); setAmount(''); await load(); } };
  if (!data && !error) return <div className="p-8 flex gap-2 text-sm text-text-secondary"><Loader2 className="w-4 h-4 animate-spin" />加载运营数据…</div>;
  if (error && !data) return <div className="p-8 text-sm text-danger">{error}</div>;
  const overview = data?.overview || {};
  return <div className="p-8 max-w-7xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold">平台运营后台</h1><p className="text-sm text-text-secondary mt-1">企业套餐、充值订单、积分流水与模型成本总览</p></div>{error && <p className="rounded-xl bg-danger/5 text-danger text-sm px-4 py-3">{error}</p>}
    <div className="grid md:grid-cols-3 xl:grid-cols-6 gap-3">{[['企业总数', overview.companyCount], ['付费企业', overview.paidCompanyCount], ['今日充值', `¥${Number(overview.todayRechargeCents || 0) / 100}`], ['本月充值', `¥${Number(overview.monthRechargeCents || 0) / 100}`], ['今日消耗', `${overview.todayCredits || 0} 积分`], ['预计毛利', `¥${Number(overview.monthGrossProfitCents || 0) / 100}`]].map(([label, value]) => <div key={String(label)} className="card p-4"><p className="text-xs text-text-muted">{label}</p><p className="text-lg font-bold mt-2">{value}</p></div>)}</div>
    <section className="card p-6"><h2 className="font-semibold flex items-center gap-2"><ShieldCheck className="w-4 h-4" />人工充值与补偿</h2><p className="text-xs text-text-muted mt-1">所有操作会写入不可删除的积分流水和审计日志。</p><div className="grid md:grid-cols-4 gap-3 mt-4"><select value={companyId} onChange={e=>setCompanyId(e.target.value)} className="input-primary text-sm"><option value="">选择企业</option>{data?.companies?.map((company:any)=><option key={company.id} value={company.id}>{company.name}</option>)}</select><input value={amount} onChange={e=>setAmount(e.target.value)} className="input-primary text-sm" placeholder="积分数量" inputMode="numeric"/><input value={reason} onChange={e=>setReason(e.target.value)} className="input-primary text-sm" placeholder="操作原因（必填）"/><div className="flex gap-2"><button disabled={busy || !companyId || !amount} onClick={()=>action({action:'grant',companyId,amount:Number(amount),sourceType:'manual'})} className="btn-primary text-xs flex-1">发放/补偿</button><button disabled={busy || !companyId || !amount} onClick={()=>action({action:'deduct',companyId,amount:Number(amount)})} className="btn-secondary text-xs flex-1">扣回</button></div></div></section>
    <section className="card p-6 overflow-auto"><h2 className="font-semibold mb-4">充值订单</h2><table className="w-full text-left text-xs"><thead className="text-text-muted"><tr><th className="pb-3">订单号</th><th>企业</th><th>金额</th><th>积分</th><th>状态</th><th /></tr></thead><tbody>{data?.orders?.map((order:any)=><tr key={order.id} className="border-t border-border-light"><td className="py-3">{order.orderNo}</td><td>{order.companyName}</td><td>¥{Number(order.amountCents)/100}</td><td>{Number(order.baseCredits)+Number(order.bonusCredits)+Number(order.firstRechargeBonus || 0)}</td><td>{order.status}</td><td>{order.status === 'pending' && <button onClick={()=>action({action:'mark_paid',orderId:order.id})} className="text-accent-blue">确认付款</button>}{order.status === 'paid' && <button onClick={()=>action({action:'refund',orderId:order.id})} className="text-danger">退款</button>}</td></tr>)}</tbody></table></section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="card p-6 overflow-auto"><h2 className="font-semibold mb-4">企业管理</h2><table className="w-full text-left text-xs"><thead className="text-text-muted"><tr><th className="pb-3">企业</th><th>套餐</th><th>积分</th><th>成员</th><th>文件</th></tr></thead><tbody>{data?.companies?.map((company:any)=><tr key={company.id} className="border-t border-border-light"><td className="py-3">{company.name}</td><td>{company.planName || '体验版'}</td><td>{company.totalBalance || 0}</td><td>{company.memberCount}</td><td>{company.fileCount}</td></tr>)}</tbody></table></div><div className="card p-6 overflow-auto"><h2 className="font-semibold mb-4">积分流水</h2><div className="space-y-3 max-h-80 overflow-auto">{data?.ledgers?.map((ledger:any)=><div key={ledger.id} className="flex justify-between text-xs border-b border-border-light pb-2"><div><p>{ledger.companyName} · {ledger.description || ledger.featureType || ledger.type}</p><p className="text-text-muted mt-1">{ledger.requestId || '—'} · {new Date(ledger.createdAt).toLocaleString('zh-CN')}</p></div><span>{Number(ledger.amount) > 0 ? '+' : ''}{ledger.amount}</span></div>)}</div></div></section>
  </div>;
}
