import { createDecipheriv, createSign, createVerify, randomBytes } from 'crypto';

const pem = (value = '') => value.replace(/\\n/g, '\n');
const required = ['WECHAT_PAY_MCH_ID','WECHAT_PAY_APP_ID','WECHAT_PAY_API_V3_KEY','WECHAT_PAY_MERCHANT_SERIAL_NO','WECHAT_PAY_PRIVATE_KEY','WECHAT_PAY_PUBLIC_KEY','WECHAT_PAY_PUBLIC_KEY_ID'];
export function isWechatPayConfigured() { return process.env.WECHAT_PAY_ENABLED === 'true' && required.every((key) => Boolean(process.env[key])); }
function config() { if (!isWechatPayConfigured()) throw new Error('微信支付通道暂未开通'); return { mchId: process.env.WECHAT_PAY_MCH_ID!, appId: process.env.WECHAT_PAY_APP_ID!, serial: process.env.WECHAT_PAY_MERCHANT_SERIAL_NO!, privateKey: pem(process.env.WECHAT_PAY_PRIVATE_KEY), publicKey: pem(process.env.WECHAT_PAY_PUBLIC_KEY), keyId: process.env.WECHAT_PAY_PUBLIC_KEY_ID!, apiV3: process.env.WECHAT_PAY_API_V3_KEY!, notifyUrl: process.env.WECHAT_PAY_NOTIFY_URL! }; }
function authorization(method: string, path: string, body: string) { const c=config(); const timestamp=Math.floor(Date.now()/1000).toString(), nonce=randomBytes(16).toString('hex'); const signer=createSign('RSA-SHA256'); signer.update(`${method}\n${path}\n${timestamp}\n${nonce}\n${body}\n`); const signature=signer.sign(c.privateKey,'base64'); return `WECHATPAY2-SHA256-RSA2048 mchid="${c.mchId}",nonce_str="${nonce}",timestamp="${timestamp}",serial_no="${c.serial}",signature="${signature}"`; }
export async function createWechatNativePayment(order: any) { const c=config(); const path='/v3/pay/transactions/native'; const body=JSON.stringify({ appid:c.appId,mchid:c.mchId,description:order.subject,out_trade_no:order.orderNo,notify_url:c.notifyUrl,amount:{total:Number(order.amountCents),currency:'CNY'} }); const response=await fetch(`https://api.mch.weixin.qq.com${path}`,{method:'POST',headers:{Authorization:authorization('POST',path,body),'Content-Type':'application/json','Accept':'application/json'},body}); const data=await response.json().catch(()=>({})); if(!response.ok || !data.code_url) throw new Error(`微信下单失败：${data.message || response.status}`); return { qrCodeUrl:data.code_url, providerOrderNo:data.prepay_id || null }; }
export async function queryWechatPayment(orderNo: string) { const c=config(); const path=`/v3/pay/transactions/out-trade-no/${encodeURIComponent(orderNo)}?mchid=${encodeURIComponent(c.mchId)}`; const response=await fetch(`https://api.mch.weixin.qq.com${path}`,{headers:{Authorization:authorization('GET',path,''),Accept:'application/json'}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(`微信查单失败：${data.message || response.status}`); return data; }
export async function parseWechatWebhook(request: Request) { const c=config(); const body=await request.text(); const timestamp=request.headers.get('wechatpay-timestamp')||'', nonce=request.headers.get('wechatpay-nonce')||'', signature=request.headers.get('wechatpay-signature')||''; const verifier=createVerify('RSA-SHA256'); verifier.update(`${timestamp}\n${nonce}\n${body}\n`); if(!verifier.verify(c.publicKey,signature,'base64')) throw new Error('微信回调签名校验失败'); const payload=JSON.parse(body); const resource=payload.resource; const decipher=createDecipheriv('aes-256-gcm',Buffer.from(c.apiV3),Buffer.from(resource.nonce,'utf8')); decipher.setAuthTag(Buffer.from(resource.ciphertext,'base64').subarray(-16)); decipher.setAAD(Buffer.from(resource.associated_data || '','utf8')); const ciphertext=Buffer.from(resource.ciphertext,'base64').subarray(0,-16); const text=Buffer.concat([decipher.update(ciphertext),decipher.final()]).toString('utf8'); return JSON.parse(text); }
