'use client';
import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { Loader2, X } from 'lucide-react';
import { useCreditBalance } from '@/hooks/useCreditBalance';

export type PurchaseIntent = { orderType: 'credit_recharge'|'plan_purchase'|'plan_renewal'|'plan_upgrade'; rechargeAmountCents?: number; planCode?: string; billingCycle?: 'monthly'|'yearly'; title: string; amountCents: number; description: string };
export default function PaymentModal({ intent, payments, onClose, onCompleted }:{intent:PurchaseIntent;payments:{wechat:boolean;alipay:boolean};onClose:()=>void;onCompleted:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[qr,setQr]=useState(''),[orderNo,setOrderNo]=useState(''); const {refreshCredits,notifyCreditsChanged}=useCreditBalance();
 useEffect(()=>{if(!orderNo)return;const timer=window.setInterval(async()=>{const res=await fetch(`/api/payments/orders/${orderNo}`);const data=await res.json();if(data.order?.status==='paid'){window.clearInterval(timer);await refreshCredits();notifyCreditsChanged();onCompleted();onClose();}},2500);return()=>window.clearInterval(timer);},[orderNo,refreshCredits,notifyCreditsChanged,onCompleted,onClose]);
 async function pay(provider:'wechat'|'alipay'){setBusy(true);setError('');try{const res=await fetch(`/api/payments/${provider}/create`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(intent)});const data=await res.json();if(!res.ok)throw new Error(data.error||'创建支付订单失败');setOrderNo(data.orderNo);if(provider==='wechat'){setQr(await QRCode.toDataURL(data.qrCodeUrl,{width:240,margin:1}));}else if(data.paymentUrl){window.location.assign(data.paymentUrl);}}catch(e:any){setError(e.message||'支付创建失败');}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 bg-black/20 flex items-center justify-center p-4"><div className="card w-full max-w-md p-6 relative"><button onClick={onClose} className="absolute top-4 right-4 text-text-muted"><X className="w-4 h-4"/></button><h2 className="text-lg font-bold">确认支付</h2><p className="text-sm text-text-secondary mt-2">{intent.title}</p><p className="text-3xl font-bold mt-4">¥{(intent.amountCents/100).toLocaleString()}</p><p className="text-xs text-text-muted mt-2">{intent.description}</p>{qr?<div className="text-center mt-5"><img src={qr} alt="微信支付二维码" className="w-60 h-60 mx-auto"/><p className="text-sm text-text-secondary mt-3">请使用微信扫码付款，正在确认支付…</p></div>:<div className="grid grid-cols-2 gap-3 mt-6"><button disabled={busy||!payments.wechat} onClick={()=>pay('wechat')} className="btn-primary text-sm disabled:opacity-40">{payments.wechat?'微信支付':'微信暂未开通'}</button><button disabled={busy||!payments.alipay} onClick={()=>pay('alipay')} className="btn-secondary text-sm disabled:opacity-40">{payments.alipay?'支付宝支付':'支付宝暂未开通'}</button></div>}{busy&&<p className="text-xs text-text-muted flex items-center justify-center gap-1 mt-3"><Loader2 className="w-3 h-3 animate-spin"/>正在创建订单…</p>}{error&&<p className="text-xs text-danger mt-3">{error}</p>}<p className="text-[10px] text-text-muted mt-4">支付成功以支付平台服务端通知或主动查单为准。</p></div></div>;
}
